consumo/urls.py
from django.conf.urls import url
from .views import ConsumoCreateView, ConsumoListView, ValorEnergeticoCreateView, \
    ValorEnergeticoListView, CostoEnergetico, get_costo_energetico

urlpatterns = [

    # Sensor
    url(r'^crear-consumo$', ConsumoCreateView.as_view(), name='crear_consumo'),
    url(r'^listar-consumo$', ConsumoListView.as_view(), name='listar_consumo'),
    url(r'^crear-valor$', ValorEnergeticoCreateView.as_view(), name='crear_valor'),
    url(r'^listar-valor$', ValorEnergeticoListView.as_view(), name='listar_valor'),
    url(r'^costo-energetico$', CostoEnergetico.as_view(), name='costo_energetico'),
    # ajax
    url(r'^get-costo$', get_costo_energetico, name='get_costo'),

]

projec_iot/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from .views import Dashboard

urlpatterns = [

    url(r'^$', Dashboard.as_view(), name='inicio'),
    url(r'^login$', auth_views.login, name='login'),
    url(r'^logout$', auth_views.logout, {'next_page': 'inicio'}, name='logout'),
    url(r'^cambiar-password/$', auth_views.password_change, name='password_change'),
    url(r'^password-cambiado/$', auth_views.password_change_done, name='password_change_done'),
    url(r'^restablecer-password/', auth_views.password_reset, name='password_reset'),
    url(r'^restablecer-password-correo-enviado/', auth_views.password_reset_done,
        name='password_reset_done'),
    url(
      r'^crear-nuevo-password/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
      auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^restablecer-password-completado/', auth_views.password_reset_complete,
        name='password_reset_complete'),

    # apps
    url(r'^gestion-sensores/', include('sensores.urls', namespace='gestion_sensores')),
    url(r'^gestion-consumo/', include('consumo.urls', namespace='gestion_consumo')),
    url(r'^gestion-estadistica/', include('estadistica.urls', namespace='gestion_estadistica')),
    url(r'^api-rest/', include('api_rest.urls', namespace='api_rest')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sensores/urls.py
from django.conf.urls import url
from .views import SensoresCreateView, SensoresListView, SensoresUpdateView

urlpatterns = [

    # Sensor
    url(r'^crear-sensor$', SensoresCreateView.as_view(), name='crear_sensor'),
    url(r'^listar-sensor$', SensoresListView.as_view(), name='listar_sensor'),
    url(r'^editar-sensor/(?P<pk>\d+)/$', SensoresUpdateView.as_view(), name='editar_sensor'),

]

sensores/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


class Sensores(models.Model):
    """
    Autor: Johan Vasquez
    Fecha: 29/04/2018
    Descripcion: Modelo para gestionar los sensores registrados en el sistema
    """
    ESTADO = (
        (0, 'ACTIVO'),
        (1, 'INACTIVO'),
    )
    UBICACION = (
        (0, 'SALA'),
        (1, 'CUARTOS'),
        (2, 'COCINA'),
        (3, 'BAÑO'),
        (4, 'COMEDOR'),
        (5, 'PATIO'),
        (5, 'OTROS...'),
    )

    nombre = models.CharField(max_length=50, verbose_name='Nombre del sensor')
    codigo = models.CharField(max_length=4, verbose_name='Código del sensor', unique=True)
    estado = models.PositiveIntegerField(choices=ESTADO)
    ubicacion = models.PositiveIntegerField(choices=UBICACION)

    def __str__(self):
        return self.nombre

sensores/forms.py
# coding=utf-8
from django import forms
from .models import Sensores


class SensoresForm(forms.ModelForm):
    """
    Autor: Johan Vasquez
    Fecha: 29/04/2018
    Descripción: Formulario para gestionar los sensores registrados en el sistema
    """
    required_css_class = 'required'

    class Meta:
        model = Sensores
        fields = ('nombre', 'codigo', 'estado', 'ubicacion')

sensores/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.views.generic import ListView, CreateView, UpdateView
from django.contrib import messages
from django.urls import reverse_lazy

from .models import Sensores
from .forms import SensoresForm


class SensoresCreateView(CreateView):
    """
    Autor: Johan Vasquez
    Fecha: 29/04/2018
    Descripción: Vista para crear sensores
    """
    model = Sensores
    form_class = SensoresForm
    success_url = reverse_lazy('gestion_sensores:listar_sensor')

    def form_valid(self, form):
        messages.success(self.request, "Sensor creado correctamente")
        return super(SensoresCreateView, self).form_valid(form)


class SensoresUpdateView(UpdateView):
    """
    Autor: Johan Vasquez
    Fecha: 29/04/2018
    Descripción: Vista para editar sensores
    """
    model = Sensores
    form_class = SensoresForm
    success_url = reverse_lazy('gestion_sensores:listar_sensor')

    def form_valid(self, form):
        if form.has_changed():
            messages.success(self.request, "Sensor actualizado correctamente")
        return super(SensoresUpdateView, self).form_valid(form)


class SensoresListView(ListView):
    """
    Autor: Johan Vasquez
    Fecha: 29/04/2018
    Descripción: Vista para Listar sensores
    """
    model = Sensores

templates/sensores/sensores_form.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load staticfiles %}

{%block titulo_pagina %}
    {% if object %} Editar {% else %} Registrar {% endif %} Afiliación
{% endblock%}

{% block titulo_panel %}
	{% if object %} Editar {% else %} Registrar {% endif %} Afiliación
{% endblock titulo_panel %}

{% block breadcrumb %}
    <li>
        <a href="{% url 'gestion_sensores:listar_sensor' %}">Sensores</a>
    </li>
    <li class="active">
        <span>{% if object %} Consultar sensor {% else %} Registrar sensor {% endif %} </span>
    </li>
{% endblock %}

{% block titulo_contenido %}
    Gestión Sensores
{% endblock %}

{% block contenido_panel_form %}

	<form id="form_sensores" action="" method="post">
		{% csrf_token %}

        <div class="row">
            <div class="col-sm-6">
                {% bootstrap_field form.nombre %}
            </div>
            <div class="col-sm-6">
                {% bootstrap_field form.codigo %}
            </div>
        </div>

        <div class="row">
            <div class="col-sm-6">
                {% bootstrap_field form.estado %}
            </div>
            <div class="col-sm-6">
                {% bootstrap_field form.ubicacion %}
            </div>
        </div>

        {% buttons %}
		    <button type="submit" class="btn btn-primary pull-right">
		      <i class="fa fa-edit"></i>
		      {% if object %} Editar {% else %} Registrar {% endif %}
		    </button>
	  	{% endbuttons %}
	</form>

{% endblock %}

{% block javascript %}
{% endblock javascript %}</html>

templates/sensores/sensores_list.html
{%extends "base.html"%}
{% load staticfiles %}

{%block titulo_panel %}
     Sensores
{% endblock%}

{%block titulo_pagina %}
     Sensor
{% endblock%}

{% block breadcrumb %}
    <li class="active">
        <span>Sensores</span>
    </li>
{% endblock %}

{% block titulo_contenido %}
    Consultar Sensores
{% endblock %}

{% block botones_panel %}
    <a href="{% url 'gestion_sensores:crear_sensor' %}" class="btn btn-primary btn-xs"><i class="fa fa-clipboard"></i> Registrar</a>
{% endblock %}

{% block contenido_panel %}
    {% if object_list %}
        <table class="table table-bordered table-hover datatable">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Código</th>
                    <th>Estado</th>
                    <th>Ubicación</th>
                    <th>Acción</th>
                </tr>
            </thead>
            <tbody>
                {% for sensor in object_list %}
                    <tr>
                        <td>{{ sensor.nombre }}</td>
                        <td>{{ sensor.codigo }}</td>
                        <td>{{ sensor.get_ubicacion_display }}</td>
                        <td>
                            {% if sensor.estado == 0 %}
                                <span class="btn label label-info btn-lg">Activo</span>
                            {% else %}
                                <span class="btn label label-danger btn-lg">Inactivo</span>
                            {% endif %}
                        </td>
                        <td>
                            <a href="{% url 'gestion_sensores:editar_sensor' sensor.pk%}" title="Editar"
                               class="btn btn-circle btn-icon-only blue-steel"><i class="fa fa-edit"></i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert alert-info" role="alert">
            No hay cargos registrados en el sistema.
        </div>
    {% endif %}
{% endblock %}

{% block javascript %}
    <script src="{% static 'js/init_datatable.js' %}"></script>
{% endblock %}