consumo/urls.py
from django.conf.urls import url
from .views import ConsumoCreateView, ConsumoListView, ValorEnergeticoCreateView, \
    ValorEnergeticoListView, CostoEnergetico, get_costo_energetico

urlpatterns = [

    # Sensor
    url(r'^crear-consumo$', ConsumoCreateView.as_view(), name='crear_consumo'),
    url(r'^listar-consumo$', ConsumoListView.as_view(), name='listar_consumo'),
    url(r'^crear-valor$', ValorEnergeticoCreateView.as_view(), name='crear_valor'),
    url(r'^listar-valor$', ValorEnergeticoListView.as_view(), name='listar_valor'),
    url(r'^costo-energetico$', CostoEnergetico.as_view(), name='costo_energetico'),
    # ajax
    url(r'^get-costo$', get_costo_energetico, name='get_costo'),

]

estadistica/urls.py
from django.conf.urls import url
from .views import Grafica, Tiempo_real, Historico

urlpatterns = [

    # Sensor
    url(r'^crear-grafica$', Grafica.as_view(), name='crear_grafica'),
    url(r'^tiempo-real$', Tiempo_real.as_view(), name='tiempo_real'),
    url(r'^crear-historico$', Historico.as_view(), name='crear_historico'),

]

projec_iot/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from .views import Dashboard

urlpatterns = [

    url(r'^$', Dashboard.as_view(), name='inicio'),
    url(r'^login$', auth_views.login, name='login'),
    url(r'^logout$', auth_views.logout, {'next_page': 'inicio'}, name='logout'),
    url(r'^cambiar-password/$', auth_views.password_change, name='password_change'),
    url(r'^password-cambiado/$', auth_views.password_change_done, name='password_change_done'),
    url(r'^restablecer-password/', auth_views.password_reset, name='password_reset'),
    url(r'^restablecer-password-correo-enviado/', auth_views.password_reset_done,
        name='password_reset_done'),
    url(
      r'^crear-nuevo-password/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
      auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^restablecer-password-completado/', auth_views.password_reset_complete,
        name='password_reset_complete'),

    # apps
    url(r'^gestion-sensores/', include('sensores.urls', namespace='gestion_sensores')),
    url(r'^gestion-consumo/', include('consumo.urls', namespace='gestion_consumo')),
    url(r'^gestion-estadistica/', include('estadistica.urls', namespace='gestion_estadistica')),
    url(r'^api-rest/', include('api_rest.urls', namespace='api_rest')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sensores/urls.py
from django.conf.urls import url
from .views import SensoresCreateView, SensoresListView, SensoresUpdateView

urlpatterns = [

    # Sensor
    url(r'^crear-sensor$', SensoresCreateView.as_view(), name='crear_sensor'),
    url(r'^listar-sensor$', SensoresListView.as_view(), name='listar_sensor'),
    url(r'^editar-sensor/(?P<pk>\d+)/$', SensoresUpdateView.as_view(), name='editar_sensor'),

]

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if !IE]><!-->
<html lang="es">
<!--<![endif]-->
<head>
	<meta charset="utf-8" />
	<title>{% block titulo_pagina %}{% endblock titulo_pagina %} SEOT</title>
	<meta content="width=device-width, initial-scale=1.0" name="viewport" />
	<meta content="" name="description" />
	<meta content="" name="author" />

	<!-- ================== BEGIN BASE CSS STYLE ================== -->
	<link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
	<link href="{% static 'assets/plugins/jquery-ui/themes/base/minified/jquery-ui.min.css' %}" rel="stylesheet" />
	<link href="{% static 'assets/plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" />
	<link href="{% static 'assets/plugins/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" />
	<link href="{% static 'assets/css/animate.min.css' %}" rel="stylesheet" />
	<link href="{% static 'assets/css/style.min.css' %}" rel="stylesheet" />
	<link href="{% static 'assets/css/style-responsive.min.css' %}" rel="stylesheet" />
	<link href="{% static 'assets/css/theme/default.css' %}" rel="stylesheet" id="theme" />
	<!-- ================== END BASE CSS STYLE ================== -->

	<!-- ================== BEGIN PAGE LEVEL STYLE ================== -->
	<link href="{% static 'assets/plugins/bootstrap-timepicker/css/bootstrap-timepicker.min.css' %}" rel="stylesheet" />
	<link href="{% static 'assets/plugins/bootstrap-datepicker/css/bootstrap-datepicker.css' %}" rel="stylesheet" />
	<link href="{% static 'assets/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.css' %}" rel="stylesheet" />
	<link href="{% static 'assets/plugins/bootstrap-eonasdan-datetimepicker/build/css/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/plugins/gritter/css/jquery.gritter.css' %}" rel="stylesheet" />

	<link href="{% static 'css/custom.css' %}" rel="stylesheet" type="text/css" />

	<!-- ================== END PAGE LEVEL STYLE ================== -->

    <!-- ================== CUSTOM PLUGINS ======================= -->
    <link href="{% static 'assets/plugins/toastr/toastr.min.css' %}" rel="stylesheet" type="text/css" />

    <link href="{% static 'assets/plugins/select2/css/select2.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'assets/plugins/select2/css/select2-bootstrap.min.css' %}" rel="stylesheet" type="text/css" />

    {% block css %} {% endblock css %}
</head>
<body>
	<!-- begin #page-loader -->
	<div id="page-loader" class="fade in"><span class="spinner"></span></div>
	<!-- end #page-loader -->

	<!-- begin #page-container -->
	<div id="page-container" class="fade page-sidebar-fixed page-header-fixed">
		<!-- begin #header -->

		<div id="header" class="header navbar navbar-default navbar-fixed-top">
			<!-- begin container-fluid -->
			<div class="container-fluid">
				<!-- begin mobile sidebar expand / collapse button -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-click="sidebar-toggled">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
				</div>
				<!-- end mobile sidebar expand / collapse button -->

				<!-- begin header navigation right -->

				<ul class="nav navbar-nav navbar-right">
                    <li class="dropdown navbar-user">
						<a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
                            {% if request.user.is_superuser %}
                                <span class="hidden-xs"> Administrador </span>
                            {% else %}
                                <span class="hidden-xs"> {{ request.user.persona.get_full_name }} </span>
                            {% endif %}
                            <b class="caret"></b>
						</a>
						<ul class="dropdown-menu animated fadeInLeft">
							<li class="arrow"></li>
							{% if not request.user.is_superuser %}
                                <li>
                                    <a href="{% url 'gestion_usuarios:perfil' %}">
                                        <i class="icon-user"></i> Ver perfil
                                    </a>
                                </li>
                            {% endif %}
                            <li>
                                <a href="{% url 'password_change' %}">
                                    <i class="icon-lock"></i> Cambiar contraseña
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href="{% url 'logout' %}">
                                    <i class="fa fa-sign-out"></i> Cerrar sesión
                                </a>
                            </li>
						</ul>
					</li>
				</ul>
				<!-- end header navigation right -->
			</div>
			<!-- end container-fluid -->
		</div>
		<!-- end #header -->

		<!-- begin #sidebar -->
		<div id="sidebar" class="sidebar">
			<!-- begin sidebar scrollbar -->
			<div data-scrollbar="true" data-height="100%">

				<!-- begin sidebar nav -->
				<ul class="nav">
					<li class="nav-header">Menú de navegación</li>
					<li class="has-sub {% if request.path == '/'%}active{% endif %}">
						<a href="{% url 'inicio' %}">
						    <i class="fa fa-home"></i>
						    <span>
						        Inicio
					        </span>
					    </a>
					</li>
					{% include 'menu-navegacion.html' %}

					<!-- begin sidebar minify button -->
					<li><a href="javascript:;" class="sidebar-minify-btn" data-click="sidebar-minify"><i class="fa fa-angle-double-left"></i></a></li>
			        <!-- end sidebar minify button -->
				</ul>
				<!-- end sidebar nav -->
			</div>
			<!-- end sidebar scrollbar -->
		</div>
		<div class="sidebar-bg"></div>
		<!-- end #sidebar -->

		<!-- begin #content -->
		<div id="content" class="content">
			<!-- begin breadcrumb -->
			<ol class="breadcrumb pull-right">
				<li {% if request.path == '/'%}class="active"{% endif %}>
                    <a href="{% url 'inicio' %}">Inicio</a>
                </li>
				{% block breadcrumb %}{% endblock breadcrumb %}
			</ol>
			<!-- end breadcrumb -->
			<!-- begin page-header -->
			<h1 class="page-header">{% block titulo_contenido %}{% endblock %}</h1>
			<!-- end page-header -->

            {% block contenido %}
                <div class="panel panel-inverse">
                    <div class="panel-heading" style="font-size: 15px">
                        <div class="panel-heading-btn">
                            {% block botones_panel %} {% endblock botones_panel %}
                        </div>
                        <h4 class="panel-title">{% block titulo_panel %} {% endblock titulo_panel %}</h4>
                    </div>
                    <div class="panel-body">

                        {% block texto_panel %}
                        {% endblock texto_panel %}

                        {% block contenido_panel %}
                            <div class="row">
                                <div class="col-xs-1"></div>
                                <div class="col-xs-10">
                                    {% block contenido_panel_form %} {% endblock contenido_panel_form %}
                                </div>
                                <div class="col-xs-1"></div>
                            </div>
                        {% endblock contenido_panel %}
                    </div>
                </div>
            {% endblock %}

		</div>
		<!-- end #content -->

		<!-- begin scroll to top btn -->
		<a href="javascript:;" class="btn btn-icon btn-circle btn-success btn-scroll-to-top fade" data-click="scroll-top"><i class="fa fa-angle-up"></i></a>
		<!-- end scroll to top btn -->
	</div>
	<!-- end page container -->

    <!-- begin #footer -->
    <div id="footer" class="footer">
        &copy; 2018 Universidad libre - Iot - Home energy control
    </div>
    <!-- end #footer -->

    <script>
        STATIC_URL = "{% static '' %}";
    </script>

	<!-- ================== BEGIN BASE JS ================== -->
	<script src="{% static 'assets/plugins/jquery/jquery-1.9.1.min.js' %}"></script>
	<script src="{% static 'assets/plugins/jquery/jquery-migrate-1.1.0.min.js' %}"></script>
	<script src="{% static 'assets/plugins/jquery-ui/ui/minified/jquery-ui.min.js' %}"></script>
	<script src="{% static 'assets/plugins/bootstrap/js/bootstrap.min.js' %}"></script>
	<!--[if lt IE 9]>
		<script src="{% static 'assets/crossbrowserjs/html5shiv.js' %}"></script>
		<script src="{% static 'assets/crossbrowserjs/respond.min.js' %}"></script>
		<script src="{% static 'assets/crossbrowserjs/excanvas.min.js' %}"></script>
	<![endif]-->
	<script src="{% static 'assets/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>
	<script src="{% static 'assets/plugins/jquery-cookie/jquery.cookie.js' %}"></script>
	<!-- ================== END BASE JS ================== -->

	<!-- ================== BEGIN PAGE LEVEL JS ================== -->
	<script src="{% static 'assets/plugins/gritter/js/jquery.gritter.js' %}"></script>
	<script src="{% static 'assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js' %}"></script>
	<script src="{% static 'assets/js/apps.min.js' %}"></script>
	<!-- ================== END PAGE LEVEL JS ================== -->

    <!-- ================== CUSTOM PLUGINS ===================== -->
    <script src="{% static 'assets/plugins/toastr/toastr.min.js' %}" type="text/javascript"></script>

	<script src="{% static 'assets/plugins/select2/js/select2.full.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'assets/plugins/select2/js/i18n/es.js' %}" type="text/javascript"></script>

    <script src="{% static 'assets/plugins/bootstrap-maxlength/bootstrap-maxlength.min.js' %}" type="text/javascript"></script>

	<script src="{% static 'assets/plugins/jquery-mask/jquery.mask.min.js' %}" type="text/javascript"></script>

    <script src="{% static 'assets/plugins/moment/moment-with-locales.min.js' %}"></script>
    <script src="{% static 'assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'assets/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.es.min.js' %}"></script>
    <script src="{% static 'assets/plugins/bootstrap-timepicker/js/bootstrap-timepicker.min.js' %}"></script>
    <script src="{% static 'assets/plugins/bootstrap-eonasdan-datetimepicker/build/js/bootstrap-datetimepicker.min.js' %}"></script>

    <script src="{% static 'js/custom.js' %}" type="text/javascript"></script>

	{% block javascript %} {% endblock javascript %}


	<script>
		$(document).ready(function() {
			App.init();
			{% for m in messages %}
				toastr["{{ m.tags }}"]('{{ m }}');
			{% endfor %}
			$.each($("span.help-block:not(.has-error span)"),function(){
                var current_block = $(this);
                var new_element = current_block.siblings("label");
                var html = "";
                html += "<span style='font-size:15px; color: #2a72b5; padding-left: 3px'>";
                html += "<i class='fa fa-question-circle' data-placement='right' data-toggle='tooltip' ";
                html += "title='" + current_block.text() + "'></i></span>";
                new_element.after(html);
                current_block.remove();
            });
			$('[data-toggle="tooltip"]').tooltip();
		});
	</script>
</body>
</html>

templates/base_login.html
{% load staticfiles %}

<!DOCTYPE html>
<!--[if IE 8]> <html lang="es" class="ie8"> <![endif]-->
<!--[if !IE]><!-->
<html lang="es">
<!--<![endif]-->
<head>
	<meta charset="utf-8" />
	<title>{% block titulo_pagina %}{% endblock %} SEOT</title>
	<meta content="width=device-width, initial-scale=1.0" name="viewport" />
	<meta content="" name="description" />
	<meta content="" name="author" />

	<!-- ================== BEGIN BASE CSS STYLE ================== -->
	<link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
	<link href="{% static 'assets/plugins/jquery-ui/themes/base/minified/jquery-ui.min.css' %}" rel="stylesheet" />
	<link href="{% static 'assets/plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" />
	<link href="{% static 'assets/plugins/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" />
	<link href="{% static 'assets/css/animate.min.css' %}" rel="stylesheet" />
	<link href="{% static 'assets/css/style.min.css' %}" rel="stylesheet" />
	<link href="{% static 'assets/css/style-responsive.min.css' %}" rel="stylesheet" />
	<link href="{% static 'assets/css/theme/default.css' %}" rel="stylesheet" id="theme" />

    {% block css %}
    {% endblock css %}

	<!-- ================== END BASE CSS STYLE ================== -->
</head>
<body>
	<!-- begin #page-loader -->
	<div id="page-loader" class="fade in"><span class="spinner"></span></div>
	<!-- end #page-loader -->

	<div class="login-cover">
        <div class="login-cover-image"><img src="{% static 'img/fondos/1.jpg' %}" data-id="login-cover-image" alt=""/></div>

	</div>
	<!-- begin #page-container -->
	<div id="page-container" class="fade">
	    <!-- begin login -->
        <div class="login login-v2" data-pageload-addclass="animated flipInX">
            <!-- begin brand -->
            <div class="login-header">
                <div class="brand">
                    <b>{% block titulo_contenido %}{% endblock %}</b>
                    <small>Home energy control</small>
                </div>
                <div class="icon">
                    {% block icon %}
                    {% endblock %}
                </div>
            </div>
            <!-- end brand -->
            <div class="login-content">
                {% block contenido %}{% endblock %}
            </div>
        </div>
        <!-- end login -->
	</div>
	<!-- end page container -->

	<!-- ================== BEGIN BASE JS ================== -->
	<script src="{% static 'assets/plugins/jquery/jquery-1.9.1.min.js' %}"></script>
	<script src="{% static 'assets/plugins/jquery-ui/ui/minified/jquery-ui.min.js' %}"></script>
	<script src="{% static 'assets/plugins/bootstrap/js/bootstrap.min.js' %}"></script>
	<!--[if lt IE 9]>
		<script src="{% static 'assets/crossbrowserjs/html5shiv.js' %}"></script>
		<script src="{% static 'assets/crossbrowserjs/respond.min.js' %}"></script>
		<script src="{% static 'assets/crossbrowserjs/excanvas.min.js' %}"></script>
	<![endif]-->
	<script src="{% static 'assets/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>
	<script src="{% static 'assets/plugins/jquery-cookie/jquery.cookie.js' %}"></script>
	<!-- ================== END BASE JS ================== -->

	<!-- ================== BEGIN PAGE LEVEL JS ================== -->
	<script src="{% static 'assets/js/login-v2.demo.min.js' %}"></script>
	<script src="{% static 'assets/js/apps.min.js' %}"></script>
	<!-- ================== END PAGE LEVEL JS ================== -->

    {% block javascript %}
    {% endblock %}

    <script>
        $('input').addClass('input-lg').parent().addClass('m-b-20');
    </script>

	<script>
		$(document).ready(function() {
		    STATIC_URL = "{% static '' %}";
			App.init();
		});
	</script>

    <script>
        var url_page = document.URL;
        var url_development = "#";
        if (url_page.indexOf(url_development) >= 0){
            $('#page-container').css('display', 'none');
            var chtml = '<div id="index-development" class="login p-20" style="text-align: center; font-size: 24px; background-color: #fff">';
            chtml += 'NOTA: <br><br><a id="lets-go" href="javascript:void()" onclick="lets_go">Continuar</a></div>';
            $("body").append(chtml);
            $("#lets-go").on('click', function(){
                $("#index-development").remove();
            $('#page-container').css('display', 'block');
            });
        }
    </script>
</body>
</html>

templates/menu-navegacion.html
    <li class="has-sub {% if 'gestion-sensores/' in request.path %}active{% endif %}">
        <a href="javascript:;" class="nav-link nav-toggle">
            <b class="caret pull-right"></b>
            <i class="fa fa-microchip"></i>
            <span class="title">Gestión Sensores</span>
        </a>
        <ul class="sub-menu">
            <li {% if 'personas/' in request.path %}class="active"{% endif %}>
                <a href="{% url 'gestion_sensores:listar_sensor' %}" class="nav-link">
                    <span class="title">Sensores</span>
                </a>
            </li>
        </ul>
    </li>

    <li class="has-sub {% if 'gestion-consumo/' in request.path %}active{% endif %}">
        <a href="javascript:;" class="nav-link nav-toggle">
            <b class="caret pull-right"></b>
            <i class="fa fa-money"></i>
            <span class="title">Gestión consumo</span>
        </a>
        <ul class="sub-menu">
            <li {% if 'listar-consumo' in request.path %}class="active"{% endif %}>
                <a href="{% url 'gestion_consumo:listar_consumo' %}" class="nav-link">
                    <span class="title">Consumo</span>
                </a>
            </li>
            <li {% if 'listar-valor' in request.path %}class="active"{% endif %}>
                <a href="{% url 'gestion_consumo:listar_valor' %}" class="nav-link">
                    <span class="title">Valor energético</span>
                </a>
            </li>
            <li {% if 'costo-energetico' in request.path %}class="active"{% endif %}>
                <a href="{% url 'gestion_consumo:costo_energetico' %}" class="nav-link">
                    <span class="title">Costo energético</span>
                </a>
            </li>
        </ul>
    </li>

    <li class="has-sub {% if 'gestion-estadistica/' in request.path %}active{% endif %}">
        <a href="javascript:;" class="nav-link nav-toggle">
            <b class="caret pull-right"></b>
            <i class="fa fa-pie-chart"></i>
            <span class="title">Gestión Estadistica</span>
        </a>
        <ul class="sub-menu">
            <li {% if 'crear-grafica' in request.path %}class="active"{% endif %}>
                <a href="{% url 'gestion_estadistica:crear_grafica' %}" class="nav-link">
                    <span class="title">Gráfica</span>
                </a>
            </li>
            <li {% if 'tiempo-real' in request.path %}class="active"{% endif %}>
                <a href="{% url 'gestion_estadistica:tiempo_real' %}" class="nav-link">
                    <span class="title">Gráfica tiempo real</span>
                </a>
            </li>
            <li {% if 'crear-historico' in request.path %}class="active"{% endif %}>
                <a href="{% url 'gestion_estadistica:crear_historico' %}" class="nav-link">
                    <span class="title">Histórico de consumo</span>
                </a>
            </li>
        </ul>
    </li>