consumo/urls.py
from django.conf.urls import url
from .views import ConsumoCreateView, ConsumoListView, ValorEnergeticoCreateView, \
    ValorEnergeticoListView, CostoEnergetico, get_costo_energetico

urlpatterns = [

    # Sensor
    url(r'^crear-consumo$', ConsumoCreateView.as_view(), name='crear_consumo'),
    url(r'^listar-consumo$', ConsumoListView.as_view(), name='listar_consumo'),
    url(r'^crear-valor$', ValorEnergeticoCreateView.as_view(), name='crear_valor'),
    url(r'^listar-valor$', ValorEnergeticoListView.as_view(), name='listar_valor'),
    url(r'^costo-energetico$', CostoEnergetico.as_view(), name='costo_energetico'),
    # ajax
    url(r'^get-costo$', get_costo_energetico, name='get_costo'),

]

projec_iot/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from .views import Dashboard

urlpatterns = [

    url(r'^$', Dashboard.as_view(), name='inicio'),
    url(r'^login$', auth_views.login, name='login'),
    url(r'^logout$', auth_views.logout, {'next_page': 'inicio'}, name='logout'),
    url(r'^cambiar-password/$', auth_views.password_change, name='password_change'),
    url(r'^password-cambiado/$', auth_views.password_change_done, name='password_change_done'),
    url(r'^restablecer-password/', auth_views.password_reset, name='password_reset'),
    url(r'^restablecer-password-correo-enviado/', auth_views.password_reset_done,
        name='password_reset_done'),
    url(
      r'^crear-nuevo-password/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
      auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^restablecer-password-completado/', auth_views.password_reset_complete,
        name='password_reset_complete'),

    # apps
    url(r'^gestion-sensores/', include('sensores.urls', namespace='gestion_sensores')),
    url(r'^gestion-consumo/', include('consumo.urls', namespace='gestion_consumo')),
    url(r'^gestion-estadistica/', include('estadistica.urls', namespace='gestion_estadistica')),
    url(r'^api-rest/', include('api_rest.urls', namespace='api_rest')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

consumo/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from datetime import datetime

from django.db import models
from sensores.models import Sensores


class ValorEnergetico(models.Model):
    """
    Autor: Johan Vasquez
    Fecha: 12/06/2018
    Descripcion: Modelo para controlar el valor de la energia
    """
    MONEDA = (
        (0, 'PESOS $(CO)'),
    )
    UNIDAD = (
        (0, 'Watts'),
    )
    TIEMPO = (
        (0, 'Segundo'),
    )
    moneda = models.PositiveIntegerField(choices=MONEDA)
    unida = models.PositiveIntegerField(choices=UNIDAD)
    tiempo = models.PositiveIntegerField(choices=TIEMPO)

    def __str__(self):
        return str(self.MONEDA[self.moneda][1]) + " " + str(self.UNIDAD[self.unida][1])


class Consumo(models.Model):
    """
    Autor: Johan Vasquez
    Fecha: 12/06/2018
    Descripcion: Modelo para contabilizar el consumo de los sensores
    """
    sensor = models.ForeignKey(Sensores)
    consumo = models.IntegerField(default=0)
    fecha = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.sensor, self.consumo, self.fecha

consumo/forms.py
# coding=utf-8
from django import forms
from .models import Consumo, ValorEnergetico, Sensores


class ValorEnergeticoForm(forms.ModelForm):
    """
    Autor: Johan Vasquez
    Fecha: 12/06/2018
    Descripción: Formulario para gestionar el valor energetico
    """
    required_css_class = 'required'

    class Meta:
        model = ValorEnergetico
        fields = ('moneda', 'unida', 'tiempo')


class ConsumoForm(forms.ModelForm):
    """
    Autor: Johan Vasquez
    Fecha: 12/06/2018
    Descripción: Formulario para gestionar el consumo energetico
    """
    required_css_class = 'required'

    class Meta:
        model = Consumo
        fields = ('sensor', 'consumo', 'fecha')


class CostoForm(forms.Form):
    """
    Autor: Johan Vasquez
    Fecha: 12/06/2018
    Descripción: Formulario para gestionar el consumo energetico
    """
    fecha_inicial = forms.DateTimeField()
    fecha_final = forms.DateTimeField()
    sensores = forms.ModelChoiceField(queryset=Sensores.objects.all())
    costo_kwh = forms.IntegerField()

    def __init__(self, *args, **kwargs):
        super(CostoForm, self).__init__(*args, **kwargs)
        self.fields['fecha_inicial'].widget.attrs.update({'class': 'datetimepicker'})
        self.fields['fecha_final'].widget.attrs.update({'class': 'datetimepicker'})
        self.fields['sensores'].queryset = Sensores.objects.all()

    required_css_class = 'required'

consumo/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from datetime import datetime

from django.views.generic import ListView, CreateView, FormView
from django.urls import reverse_lazy
from django.http import JsonResponse

from .models import Consumo, ValorEnergetico
from .forms import ConsumoForm, ValorEnergeticoForm, CostoForm


class ConsumoCreateView(CreateView):
    """
    Autor: Johan Vasquez
    Fecha: 12/06/2018
    Descripción: Vista para crear consumo energetico
    """
    model = Consumo
    form_class = ConsumoForm
    success_url = reverse_lazy('gestion_consumo:listar_consumo')


class ConsumoListView(ListView):
    """
    Autor: Johan Vasquez
    Fecha: 12/06/2018
    Descripción: Vista para Listar el consumo energetico
    """
    model = Consumo


class ValorEnergeticoCreateView(CreateView):
    """
    Autor: Johan Vasquez
    Fecha: 12/06/2018
    Descripción: Vista para crear consumo energetico
    """
    model = ValorEnergetico
    form_class = ValorEnergeticoForm
    success_url = reverse_lazy('gestion_consumo:listar_valor')


class ValorEnergeticoListView(ListView):
    """
    Autor: Johan Vasquez
    Fecha: 12/06/2018
    Descripción: Vista para Listar el consumo energetico
    """
    model = ValorEnergetico


class CostoEnergetico(FormView):
    form_class = CostoForm
    template_name = 'consumo/costo_energetico.html'


def get_costo_energetico(request):
    """
    """
    if request.is_ajax():
        fecha_desde = str(request.POST["data[fecha_inicial]"])
        fecha_desde = datetime.strptime(fecha_desde, "%d/%m/%Y %H:%M")
        fecha_hasta = str(request.POST["data[fecha_final]"])
        fecha_hasta = datetime.strptime(fecha_hasta,  "%d/%m/%Y %H:%M")
        id_sensor = str(request.POST["data[id_sensor]"])
        costo_kwh = int(request.POST["data[costo_kwh]"])

        if fecha_desde and fecha_hasta and id_sensor and costo_kwh:
            consumo_total = Consumo.objects.filter(sensor_id=id_sensor, fecha__range=[fecha_desde,
                                                                                      fecha_hasta]).all()
            count = 0
            for consumo in consumo_total:
                count += consumo.consumo
            response = {"costo": float((count*costo_kwh)/1000)}
            return JsonResponse(response)
        else:
            response = {"Error": "Dato faltante"}
            return JsonResponse(response)

templates/consumo/consumo_form.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load staticfiles %}

{%block titulo_pagina %}
    {% if object %} Editar {% else %} Registrar {% endif %} Consumo Energetico
{% endblock%}

{% block titulo_panel %}
	{% if object %} Editar {% else %} Registrar {% endif %} Consumo Energetico
{% endblock titulo_panel %}

{% block breadcrumb %}
    <li>
        <a href="{% url 'gestion_consumo:listar_consumo' %}">Consumo Energetico</a>
    </li>
    <li class="active">
        <span>{% if object %} Consultar sensor {% else %} Registrar Consumo Energetico {% endif %} </span>
    </li>
{% endblock %}

{% block titulo_contenido %}
    Consumo Energetico
{% endblock %}

{% block contenido_panel_form %}

	<form id="form_sensores"  method="post">
		{% csrf_token %}

        <div class="row">
            <div class="col-sm-6">
                {% bootstrap_field form.sensor %}
            </div>
            <div class="col-sm-6">
                {% bootstrap_field form.consumo %}
            </div>
        </div>

        <div class="row">
            <div class="col-sm-6">
                {% bootstrap_field form.fecha %}
            </div>
            <div class="col-sm-6">
                {% buttons %}
                    <button type="submit" class="btn btn-primary pull-right">
                      <i class="fa fa-edit"></i>
                      {% if object %} Editar {% else %} Registrar {% endif %}
                    </button>
                {% endbuttons %}
            </div>
        </div>
	</form>

{% endblock %}

templates/consumo/consumo_list.html
{%extends "base.html"%}
{% load staticfiles %}

{%block titulo_panel %}
     Consumo Energetico
{% endblock%}

{%block titulo_pagina %}
     Consumo Energetico
{% endblock%}

{% block breadcrumb %}
    <li class="active">
        <span>Consumo Energetico</span>
    </li>
{% endblock %}

{% block titulo_contenido %}
    Consultar Consumo Energetico
{% endblock %}

{% block botones_panel %}
    <a href="{% url 'gestion_consumo:crear_consumo' %}" class="btn btn-primary btn-xs"><i class="fa fa-clipboard"></i> Registrar</a>
{% endblock %}

{% block contenido_panel %}
    {% if object_list %}
        <table class="table table-bordered table-hover datatable">
            <thead>
                <tr>
                    <th>Sensor</th>
                    <th>Consumo</th>
                    <th>Fecha</th>
                </tr>
            </thead>
            <tbody>
                {% for consumo in object_list %}
                    <tr>
                        <td>{{ consumo.sensor }}</td>
                        <td>{{ consumo.consumo }}</td>
                        <td>{{ consumo.fecha|date:'Y-m-d H:i:s' }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert alert-info" role="alert">
            No hay cargos registrados en el sistema.
        </div>
    {% endif %}
{% endblock %}

{% block javascript %}
    <script src="{% static 'js/init_datatable.js' %}"></script>
{% endblock %}

templates/consumo/costo_energetico.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load staticfiles %}

{%block titulo_pagina %}
    Costo Energético
{% endblock%}

{% block titulo_panel %}
	Costo Energético
{% endblock titulo_panel %}

{% block breadcrumb %}
    <li>
        <a href="{% url 'gestion_consumo:listar_consumo' %}">Consumo Energético</a>
    </li>
{% endblock %}

{% block titulo_contenido %}
    Costo Energético
{% endblock %}

{% block contenido_panel_form %}

	<form id="form_sensores"  method="post">
		{% csrf_token %}
            <div class="row">
                <div class="col-sm-6">
                     {% bootstrap_field form.fecha_inicial %}
                </div>
                <div class="col-sm-6">
                    {% bootstrap_field form.fecha_final %}
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                     {% bootstrap_field form.sensores %}
                </div>
                <div class="col-sm-6">
                     {% bootstrap_field form.costo_kwh %}
                </div>
            </div>
            <div class="alert alert-info fade in m-b-15" id="costo-final">
            </div>
	</form>

{% endblock %}


{% block javascript %}

    <script type="text/javascript">
        var token = '{{csrf_token}}';

        function get_opciones(select1, select2, msj, url_request, token) {
            var dataString = {};
            dataString['data']=select1;
            dataString['csrfmiddlewaretoken']=token;
            var posteo =  $.post(url_request, dataString,function(res){
                $(select2).find('option:not(:first)').remove();
                if(res!="error"){
                    costo = res['costo'];
                    costo =  costo.toFixed(2).replace(/\d(?=(\d{3})+\.)/g, '$&,');
                     $("#costo").remove();
                     $("#costo-final").append($("<h3 id=costo value='"+costo+ "'></h3>").text("$ " + costo));

                }else{
                    alert(msj);
                }
            });
        }
    </script>

    <script type="text/javascript">
        var token = '{{ csrf_token }}';
        $(document).ready(function () {
            $("#id_costo_kwh").change(function(){
                var msj = "Ocurrió un error al traer los cargos";
                var data = {"fecha_inicial": $("#id_fecha_inicial").val(),
                    "fecha_final": $("#id_fecha_final").val(),
                    "id_sensor": $("#id_sensores").val(),
                    "costo_kwh": $("#id_costo_kwh").val()}
                var url_get = "{% url 'gestion_consumo:get_costo' %}";
                var tipo = $(this);
                get_opciones(data, tipo, msj, url_get, token);
            });
        });
    </script>
{% endblock javascript %}

templates/consumo/valorenergetico_form.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load staticfiles %}

{%block titulo_pagina %}
    {% if object %} Editar {% else %} Registrar {% endif %} Valor Energetico
{% endblock%}

{% block titulo_panel %}
	{% if object %} Editar {% else %} Registrar {% endif %} Valor Energetico
{% endblock titulo_panel %}

{% block breadcrumb %}
    <li>
        <a href="{% url 'gestion_consumo:listar_valor' %}">Valor Energetico</a>
    </li>
    <li class="active">
        <span>{% if object %} Consultar sensor {% else %} Registrar Valor Energetico {% endif %} </span>
    </li>
{% endblock %}

{% block titulo_contenido %}
    Valor Energetico
{% endblock %}

{% block contenido_panel_form %}

	<form id="form_sensores" method="post">
		{% csrf_token %}
        <div class="row">
            <div class="col-sm-4">
                {% bootstrap_field form.unida %}
            </div>
            <div class="col-sm-4">
                {% bootstrap_field form.moneda %}
            </div>
            <div class="col-sm-4">
                {% bootstrap_field form.tiempo %}
            </div>
        </div>


        {% buttons %}
		    <button type="submit" class="btn btn-primary pull-right">
		      <i class="fa fa-edit"></i>
		      {% if object %} Editar {% else %} Registrar {% endif %}
		    </button>
	  	{% endbuttons %}
	</form>

{% endblock %}

templates/consumo/valorenergetico_list.html
{%extends "base.html"%}
{% load staticfiles %}

{%block titulo_panel %}
     Valor Energetico
{% endblock%}

{%block titulo_pagina %}
     Valor Energetico
{% endblock%}

{% block breadcrumb %}
    <li class="active">
        <span>Valor Energetico</span>
    </li>
{% endblock %}

{% block titulo_contenido %}
    Valor Energetico
{% endblock %}

{% block botones_panel %}
    <a href="{% url 'gestion_consumo:crear_valor' %}" class="btn btn-primary btn-xs"><i class="fa fa-clipboard"></i> Registrar</a>
{% endblock %}

{% block contenido_panel %}
    {% if object_list %}
        <table class="table table-bordered table-hover datatable">
            <thead>
                <tr>
                    <th>Moneda</th>
                    <th>Unidad</th>
                    <th>Tiempo</th>
                </tr>
            </thead>
            <tbody>
                {% for valor in object_list %}
                    <tr>
                        <td>{{ valor.get_moneda_display }}</td>
                        <td>{{ valor.get_unida_display }}</td>
                        <td>{{ valor.get_tiempo_display }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert alert-info" role="alert">
            No hay cargos registrados en el sistema.
        </div>
    {% endif %}
{% endblock %}

{% block javascript %}
    <script src="{% static 'js/init_datatable.js' %}"></script>
{% endblock %}